---
wg_quick_interface_name: ~
wg_quick_interface_address: ~
wg_quick_interface_listen_port: ~
wg_quick_interface_private_key: ~
wg_quick_interface_private_key_file: ~
wg_quick_interface_peer_endpoint: ~
wg_quick_interface_peer_public_key: ~
wg_quick_interface_peer_allowed_ips: ~

wg_quick_interfaces:
  - name: "{{ wg_quck_interface_name }}"
    address: "{{ wg_quick_interface_address }}"
    listen_port: "{{ wg_quick_interface_listen_port }}"
    private_key: "{{ wg_quick_interface_private_key }}"
    private_key_file: "{{ wg_quick_interface_private_key_file }}"
    peers:
      - endpoint: "{{ wg_quick_interface_peer_endpoint }}"
        public_key: "{{ wg_quick_interface_peer_public_key }}"
        allowed_ips: "{{ wg_quick_interface_peer_allowed_ips }}"
