---
caddy_config: |+2
  {
        auto_https disable_redirects
  }

  (proxyheaders) {
      header_up X-Forwarded-Ssl on
      header_up Host {host}
      header_up X-Real-IP {remote}
      header_up X-Forwarded-For {remote}
      # header_up X-Forwarded-Port {port}
      header_up X-Forwarded-Proto {scheme}
      header_up X-Url-Scheme {scheme}
      header_up X-Forwarded-Host {host}
  }
  
  # Import all configurations
  import {{ caddy_dynamic_configs_dir }}/*/Caddyfile
  
  :80 {
      redir /  https://{host}{uri} 301
  }
